param(
    [string]$Release = "latest",
    [string]$Registry = "ghcr.io/caibility1/smri_pipeline_win",
    [string]$OfflineArchive = "",
    [string]$FsLicenseSource = "",
    [string]$WslDistro = "Ubuntu-22.04",
    [bool]$MaterializeResources = $true,
    [switch]$ForceResources
)

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$LocalImage = "smri_pipeline_win:full-portable"
$RemoteImage = if ($Release -eq "latest") { "${Registry}:full-latest" } else { "${Registry}:full-$Release" }

function Invoke-Docker([string[]]$Arguments) {
    & docker @Arguments
    if ($LASTEXITCODE -ne 0) { throw "docker $($Arguments -join ' ') failed" }
}

function Test-NativeProbe([scriptblock]$Probe) {
    $PreviousErrorAction = $ErrorActionPreference
    try {
        $ErrorActionPreference = "SilentlyContinue"
        & $Probe 1>$null 2>$null
        return $LASTEXITCODE -eq 0
    } finally {
        $ErrorActionPreference = $PreviousErrorAction
    }
}

function Test-NonEmptyDirectory([string]$Path) {
    return (Test-Path -LiteralPath $Path) -and $null -ne (Get-ChildItem -LiteralPath $Path -Force -ErrorAction SilentlyContinue | Select-Object -First 1)
}

function Convert-ToWslPath([string]$WindowsPath) {
    $Resolved = [IO.Path]::GetFullPath($WindowsPath)
    if ($Resolved -notmatch '^([A-Za-z]):\\(.*)$') { throw "WSL conversion requires a drive-letter path: $Resolved" }
    $Drive = $Matches[1].ToLowerInvariant()
    $Rest = $Matches[2].Replace('\', '/')
    return "/mnt/$Drive/$Rest"
}

if (-not (Test-NativeProbe { & docker version })) { throw "Docker Desktop is not running." }

if ($OfflineArchive) {
    $Archive = (Resolve-Path -LiteralPath $OfflineArchive).ProviderPath
    Write-Host "Loading portable image from $Archive"
    Invoke-Docker @("load", "--input", $Archive)
    if (-not (Test-NativeProbe { & docker image inspect $LocalImage })) {
        throw "Archive did not provide expected image: $LocalImage"
    }
} else {
    Write-Host "Pulling $RemoteImage"
    Invoke-Docker @("pull", $RemoteImage)
    Invoke-Docker @("tag", $RemoteImage, $LocalImage)
}

if ($MaterializeResources) {
    $Targets = @(
        @{ Source = "/opt/smri/models/nnUNet"; Destination = "resources\models\nnUNet" },
        @{ Source = "/opt/smri/models/denoise_diffusion/CBCP_UnDPM_with_age_finetune"; Destination = "resources\models\denoise_diffusion\CBCP_UnDPM_with_age_finetune" },
        @{ Source = "/opt/smri/workbench"; Destination = "resources\software\workbench-linux64-v2.0.0\workbench" },
        @{ Source = "/opt/smri/templates"; Destination = "resources\templates" }
    )
    $ContainerId = (& docker create $LocalImage).Trim()
    if ($LASTEXITCODE -ne 0 -or -not $ContainerId) { throw "docker create failed for resource export" }
    try {
        foreach ($Target in $Targets) {
            $Destination = Join-Path $RepoRoot $Target.Destination
            if ((Test-NonEmptyDirectory $Destination) -and -not $ForceResources) {
                Write-Host "Keeping existing resource: $Destination"
                continue
            }
            New-Item -ItemType Directory -Force -Path $Destination | Out-Null
            Write-Host "Restoring $($Target.Source) -> $Destination"
            docker cp "${ContainerId}:$($Target.Source)/." $Destination
            if ($LASTEXITCODE -ne 0) { throw "docker cp failed for $($Target.Source)" }
        }
    } finally {
        docker rm $ContainerId *> $null
    }
}

$DefaultLicense = Join-Path $RepoRoot "resources\software\freesurfer\license.txt"
if ($FsLicenseSource) {
    $LicenseSource = (Resolve-Path -LiteralPath $FsLicenseSource).ProviderPath
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $DefaultLicense) | Out-Null
    Copy-Item -LiteralPath $LicenseSource -Destination $DefaultLicense -Force
    Write-Host "FreeSurfer license copied to $DefaultLicense"

    $WslLicenseSource = Convert-ToWslPath $DefaultLicense
    if (Test-NativeProbe { & wsl.exe -d $WslDistro -- true }) {
        & wsl.exe -d $WslDistro -u root -- install -D -m 0644 $WslLicenseSource /usr/local/freesurfer/license.txt
        if ($LASTEXITCODE -ne 0) { throw "Failed to copy license into WSL" }
        Write-Host "FreeSurfer license copied to WSL /usr/local/freesurfer/license.txt"
    } else {
        Write-Warning "WSL distro $WslDistro is not ready; Docker license copy is complete."
    }
}

$DockerEnv = Join-Path $RepoRoot "environment\docker_env.local.ps1"
$EnvText = @"
# Generated by docker/install_portable.ps1
`$env:SMRI_DOCKER_AI_IMAGE = "$LocalImage"
`$env:SMRI_DOCKER_TOOLS_IMAGE = "$LocalImage"
`$env:SMRI_DOCKER_GPUS = "all"
`$env:SMRI_DOCKER_BUNDLED_RESOURCES = "1"
`$env:FSLDIR = "/opt/fsl"
`$env:FREESURFER_HOME = "/opt/freesurfer"
`$env:ANTSPATH = "/opt/smri/tools-env/bin"
`$env:SMRI_REGISTRATION_BACKEND = "docker"
`$env:SMRI_NNUNET_BACKEND = "docker"
`$env:SMRI_MASK_BACKEND = "windows"
`$env:SMRI_ACPC_BACKEND = "docker"
`$env:SMRI_DENOISE_BACKEND = "docker"
`$env:SMRI_PRESURF_BACKEND = "windows"
`$env:SMRI_RECON_BACKEND = "docker"
"@
[IO.File]::WriteAllText($DockerEnv, $EnvText, [Text.UTF8Encoding]::new($false))

$Manifest = [ordered]@{
    installed_at = (Get-Date).ToString("o")
    release = $Release
    source_image = if ($OfflineArchive) { $OfflineArchive } else { $RemoteImage }
    local_image = $LocalImage
    bundled_resources = $true
}
$ManifestPath = Join-Path $RepoRoot "resources\portable_release.json"
$Manifest | ConvertTo-Json | Set-Content -LiteralPath $ManifestPath -Encoding UTF8

Write-Host "Portable Docker setup complete."
Write-Host "Load environment with: . .\environment\docker_env.local.ps1"
